#pragma once


// ...
#define  pKEY__CH_PERCENT_VALUE				"CH.PERCENT_VALUE"
#define  pKEY__DATA_BACK_COLOR				"DATA.BACK_COLOR"
#define  pKEY__DATA_DEFAULT_COLOR			"DATA.DEFAULT.COLOR"

#define  pKEY__CH_PERCENT_STATE				"CH.PERCENT_STATE"
#define  pKEY__DATA_STATE_1					"DATA.STATE.1"
#define  pKEY__DATA_STATE_2					"DATA.STATE.2"
#define  pKEY__DATA_STATE_3					"DATA.STATE.3"
#define  pKEY__DATA_STATE_4					"DATA.STATE.4"
#define  pKEY__DATA_COLOR_1					"DATA.COLOR.1"
#define  pKEY__DATA_COLOR_2					"DATA.COLOR.2"
#define  pKEY__DATA_COLOR_3					"DATA.COLOR.3"
#define  pKEY__DATA_COLOR_4					"DATA.COLOR.4"

#define  pKEY__DATA_TEXT_ALIGN				"DATA.TEXT_ALIGN"
#define  pKEY__DATA_TEXT_COLOR				"DATA.TEXT_COLOR"

#define  pKEY__DATA_FONT_NAME				"DATA.FONT_NAME"
#define  pKEY__DATA_FONT_WIDTH				"DATA.FONT_WIDTH"
#define  pKEY__DATA_FONT_HEIGHT				"DATA.FONT_HEIGHT"

#define  pKEY__DATA_DISPLAY_UNIT			"DATA.DISPLAY_UNIT"

// ...
#define  pKEY__TEST_PERCENT_VALUE			"TEST.PERCENT_VALUE"
#define  pKEY__TEST_PERCENT_STATE			"TEST.PERCENT_STATE"
