#pragma once


// ...
#define  pKEY__CH_FEEDBACK					"CH.FEEDBACK"
#define  pKEY__DATA_FEEDBACK				"DATA.FEEDBACK"

#define  pKEY__DATA_DIR_SUB					"DATA.DIR_SUB"
#define  pKEY__DATA_FILE_NAME				"DATA.FILE_NAME"

#define  pKEY__DATA_FONT_NAME				"DATA.FONT_NAME"
#define  pKEY__DATA_FONT_WIDTH				"DATA.FONT_WIDTH"
#define  pKEY__DATA_FONT_HEIGHT				"DATA.FONT_HEIGHT"
#define  pKEY__DATA_EDGE_WIDTH				"DATA.EDGE_WIDTH"
#define  pKEY__DATA_EDGE_UP_COLOR			"DATA.EDGE_UP_COLOR"
#define  pKEY__DATA_EDGE_DOWN_COLOR			"DATA.EDGE_DOWN_COLOR"

#define  pKEY__DATA_TITLE_TEXT		        "DATA.TITLE_TEXT"
#define  pKEY__DATA_TEXT_P_COLOR			"DATA.TEXT_P_COLOR"
#define  pKEY__DATA_TEXT_R_COLOR			"DATA.TEXT_R_COLOR"
#define  pKEY__DATA_BACK_P_COLOR			"DATA.BACK_P_COLOR"
#define  pKEY__DATA_BACK_R_COLOR			"DATA.BACK_R_COLOR"
