#pragma once


// ...
#define  pKEY__DATA_BUTTON_TYPE						"DATA.BUTTON_TYPE"
#define  pKEY__CH_STATE								"CH.STATE"
#define  pKEY__DATA_INIT_TITLE						"DATA.INIT_TITLE"
#define  pKEY__DATA_FONT_NAME						"DATA.FONT_NAME"
#define  pKEY__DATA_TEXT_COLOR						"DATA.TEXT_COLOR"
#define  pKEY__DATA_BACK_COLOR						"DATA.BACK_COLOR"
#define  pKEY__DATA_TEXT_WIDTH						"DATA.TEXT_WIDTH"
#define  pKEY__DATA_TEXT_HEIGHT						"DATA.TEXT_HEIGHT"
#define  pKEY__DATA_TEXT_WEIGHT						"DATA.TEXT_WEIGHT"
#define  pKEY__DATA_EDGE_WIDTH						"DATA.EDGE_WIDTH"
#define  pKEY__DATA_EDGE_UP_COLOR					"DATA.EDGE_UP_COLOR"
#define  pKEY__DATA_EDGE_DOWN_COLOR					"DATA.EDGE_DOWN_COLOR"
#define  pKEY__DATA_OUTLINE_COLOR			        "DATA.OUTLINE_COLOR"

#define  pKEY__DATA_TEXT_Y_POS_OFFSET				"DATA.TEXT.Y_POS.OFFSET"

