#pragma once


// ...
#define  pKEY__ACTIVE_DISPLAY_PRESSED				"ACTIVE.DISPLAY_PRESSED"
#define  pKEY__CH_DISPLAY_PRESSED					"CH.DISPLAY_PRESSED"
#define  pKEY__DATA_DISPLAY_PRESSED					"DATA.DISPLAY_PRESSED"

//
#define  pKEY__CH_SET_01							"CH.SET"
#define  pKEY__CH_SET_02							"CH.SET.02"

#define  pKEY__DATA_TITLE_TEXT						"DATA.TITLE_TEXT"

#define  pKEY__DATA_FONT_NAME						"DATA.FONT_NAME"
#define  pKEY__DATA_TEXT_COLOR						"DATA.TEXT_COLOR"
#define  pKEY__DATA_BACK_COLOR						"DATA.BACK_COLOR"
#define  pKEY__DATA_TEXT_WIDTH						"DATA.TEXT_WIDTH"
#define  pKEY__DATA_TEXT_HEIGHT						"DATA.TEXT_HEIGHT"
#define  pKEY__DATA_TEXT_WEIGHT						"DATA.TEXT_WEIGHT"
#define  pKEY__DATA_EDGE_WIDTH						"DATA.EDGE_WIDTH"
#define  pKEY__DATA_EDGE_UP_COLOR					"DATA.EDGE_UP_COLOR"
#define  pKEY__DATA_EDGE_DOWN_COLOR					"DATA.EDGE_DOWN_COLOR"
#define  pKEY__DATA_OUTLINE_COLOR			        "DATA.OUTLINE_COLOR"

#define  pKEY__DATA_TEXT_Y_POS_OFFSET				"DATA.TEXT.Y_POS.OFFSET"

