#pragma once


// ...
#define  pKEY__DATA_COMMENT							"DATA.COMMENT"

#define  pKEY__CH_FEEDBACK_1						"CH.FEEDBACK.1"
#define  pKEY__CH_FEEDBACK_2						"CH.FEEDBACK.2"
#define  pKEY__DATA_SET_DATA_1						"DATA.SET_DATA.1"
#define  pKEY__DATA_SET_DATA_2						"DATA.SET_DATA.2"

#define  pKEY__CH_DISPLAY_1							"CH.DISPLAY.1"
#define  pKEY__CH_DISPLAY_2							"CH.DISPLAY.2"
#define  pKEY__CH_DISPLAY_3							"CH.DISPLAY.3"
#define  pKEY__CH_DISPLAY_4							"CH.DISPLAY.4"
#define  pKEY__CH_DISPLAY_5							"CH.DISPLAY.5"
#define  pKEY__DATA_DISPLAY_STS_1					"DATA.DISPLAY_STS.1"
#define  pKEY__DATA_DISPLAY_STS_2					"DATA.DISPLAY_STS.2"
#define  pKEY__DATA_DISPLAY_STS_3					"DATA.DISPLAY_STS.3"
#define  pKEY__DATA_DISPLAY_STS_4					"DATA.DISPLAY_STS.4"
#define  pKEY__DATA_DISPLAY_STS_5					"DATA.DISPLAY_STS.5"

#define  pKEY__CH_SET_1								"CH.SET.1"
#define  pKEY__CH_SET_2								"CH.SET.2"

#define  pKEY__DATA_LOCK_CONDITION					"DATA.LOCK.CONDITION"
#define  pKEY__CH_LOCK_STS							"CH.LOCK_STS"
#define  pKEY__DATA_LOCK_STS_1						"DATA.LOCK_STS.1"
#define  pKEY__DATA_LOCK_STS_2						"DATA.LOCK_STS.2"
#define  pKEY__DATA_LOCK_STS_3						"DATA.LOCK_STS.3"
#define  pKEY__DATA_LOCK_STS_4						"DATA.LOCK_STS.4"
#define  pKEY__DATA_LOCK_STS_5						"DATA.LOCK_STS.5"
#define  pKEY__DATA_LOCK_STS_6						"DATA.LOCK_STS.6"
#define  pKEY__DATA_LOCK_STS_7						"DATA.LOCK_STS.7"
#define  pKEY__DATA_LOCK_STS_8						"DATA.LOCK_STS.8"
#define  pKEY__CH_LOCK_STS2							"CH.LOCK_STS2"
#define  pKEY__DATA_LOCK_STS2_1						"DATA.LOCK_STS2.1"
#define  pKEY__DATA_LOCK_STS2_2						"DATA.LOCK_STS2.2"
#define  pKEY__DATA_LOCK_STS2_3						"DATA.LOCK_STS2.3"
#define  pKEY__DATA_LOCK_STS2_4						"DATA.LOCK_STS2.4"
#define  pKEY__DATA_LOCK_STS2_5						"DATA.LOCK_STS2.5"
#define  pKEY__DATA_LOCK_STS2_6						"DATA.LOCK_STS2.6"
#define  pKEY__DATA_LOCK_STS2_7						"DATA.LOCK_STS2.7"
#define  pKEY__DATA_LOCK_STS2_8						"DATA.LOCK_STS2.8"

#define  pKEY__DATA_INACTIVE_COLOR                  "DATA.INACTIVE_COLOR"

#define  pKEY__DATA_FONT_NAME						"DATA.FONT_NAME"
#define  pKEY__DATA_FONT_WIDTH						"DATA.FONT_WIDTH"
#define  pKEY__DATA_FONT_HEIGHT						"DATA.FONT_HEIGHT"
#define  pKEY__DATA_EDGE_WIDTH						"DATA.EDGE_WIDTH"
#define  pKEY__DATA_EDGE_UP_COLOR					"DATA.EDGE_UP_COLOR"
#define  pKEY__DATA_EDGE_DOWN_COLOR					"DATA.EDGE_DOWN_COLOR"

#define  pKEY__DATA_TITLE_TEXT_1			        "DATA.TITLE_TEXT.1"
#define  pKEY__DATA_TITLE_TEXT_2			        "DATA.TITLE_TEXT.2"
#define  pKEY__DATA_TITLE_COLOR_1			        "DATA.TITLE_COLOR.1"
#define  pKEY__DATA_TITLE_COLOR_2			        "DATA.TITLE_COLOR.2"
#define  pKEY__DATA_BACK_COLOR_1			        "DATA.BACK_COLOR.1"
#define  pKEY__DATA_BACK_COLOR_2			        "DATA.BACK_COLOR.2"
#define  pKEY__DATA_OUTLINE_COLOR			        "DATA.OUTLINE_COLOR"

#define  pKEY__DATA_ACTION_CONFIRM			        "DATA.ACTION_CONFIRM"


// ...
#define  pKEY__TEST_CH_DISPLAY_1					"TEST.CH.DISPLAY.1"
#define  pKEY__TEST_CH_DISPLAY_2					"TEST.CH.DISPLAY.2"
#define  pKEY__TEST_CH_DISPLAY_3					"TEST.CH.DISPLAY.3"
#define  pKEY__TEST_CH_DISPLAY_4					"TEST.CH.DISPLAY.4"
#define  pKEY__TEST_CH_DISPLAY_5					"TEST.CH.DISPLAY.5"

#define  pKEY__TEST_CH_LOCK_STS						"TEST.CH.LOCK_STS"
#define  pKEY__TEST_CH_LOCK_STS2					"TEST.CH.LOCK_STS2"

#define  pKEY__TEST_POPUP_MODE						"TEST.POUP_MODE"

#define  pKEY__TEST_DEBUG_MODE						"TEST.DEBUG_MODE"
