#pragma once


// ...
#define  ACT__RETRY								"RETRY"
#define  ACT__ABORT								"ABORT"

// ...
#define  ALID__VALVE_OPEN__TIMEOUT							1
#define  ALID__SLOT_VALVE_PM_CLOSE__TIMEOUT					2
#define  ALID__SLOT_VALVE_TM_CLOSE__TIMEOUT					3
#define  ALID__VAC_RB_NOT_RETRACTED							4
#define  ALID__SV_OPEN__NOT_ATM_ERROR						5
#define  ALID__SV_OPEN__NOT_VAC_ERROR						6
#define  ALID__VALVE_PM_SV_NOT_UP_ACTION_CONDITION			7
#define  ALID__MAX_DIFFER_PRESS_ALARM						8
#define  ALID__PM_NOT_EXIST_CONFIG_ALARAM					9

#define  ALID__SV_CLOSE_NOT_EQUAL_PRESSURE_ALARAM			10
#define  ALID__TMC_PMC_PRESSURE_IS_NOT_SAME					11
