#pragma once


// ...
#define  ACT__RETRY										"RETRY"
#define  ACT__IGNORE									"IGNORE"
#define  ACT__ABORT										"ABORT"
#define  ACT__YES										"YES"
#define  ACT__NO										"NO"


// ...
#define  ALID__ARM_A__MATERIAL_EXIST_ERROR						1
#define  ALID__ARM_B__MATERIAL_EXIST_ERROR						2
#define  ALID__AFTER_MAPPING_CROSSED_WAFER_DETECTED				3

#define  ALID__LP1__MATERIAL_EXIST_ERROR						11
#define  ALID__LP2__MATERIAL_EXIST_ERROR						12
#define  ALID__LP3__MATERIAL_EXIST_ERROR						13
#define  ALID__LP4__MATERIAL_EXIST_ERROR						14
#define  ALID__LP5__MATERIAL_EXIST_ERROR						15

#define  ALID__AL1__MATERIAL_EXIST_ERROR						21
#define  ALID__LBA__MATERIAL_EXIST_ERROR						22
#define  ALID__LBB__MATERIAL_EXIST_ERROR						23
#define  ALID__VIS1__MATERIAL_EXIST_ERROR						24

#define  ALID__SIDE_STORAGE1__MATERIAL_EXIST_ERROR				25
#define  ALID__SIDE_STORAGE2__MATERIAL_EXIST_ERROR				26		

#define  ALID__PMx__MATERIAL_EXIST_ERROR						31
#define  ALID__ALx__SLOT_ID_ERROR								32
#define  ALID__LLx__SLOT_ID_ERROR								33

//
#define  ALID__ARM_A__MATERIAL_NONE_ERROR						41
#define  ALID__ARM_B__MATERIAL_NONE_ERROR						42

#define  ALID__LP1__MATERIAL_NONE_ERROR							51
#define  ALID__LP2__MATERIAL_NONE_ERROR							52
#define  ALID__LP3__MATERIAL_NONE_ERROR							53
#define  ALID__LP4__MATERIAL_NONE_ERROR							54
#define  ALID__LP5__MATERIAL_NONE_ERROR							55

#define  ALID__AL1__MATERIAL_NONE_ERROR							61
#define  ALID__LBA__MATERIAL_NONE_ERROR							62
#define  ALID__LBB__MATERIAL_NONE_ERROR							63
#define  ALID__VIS1__MATERIAL_NONE_ERROR						64

#define  ALID__SIDE_STORAGE1__MATERIAL_NONE_ERROR				65			
#define  ALID__SIDE_STORAGE2__MATERIAL_NONE_ERROR				66			

#define  ALID__PMx__MATERIAL_NONE_ERROR							71
#define  ALID__STN__NOT_EXIST_ERROR								72

#define  ALID__LBA__NOT_DOOR_OPEN								81
#define  ALID__LBB__NOT_DOOR_OPEN								82
#define  ALID__LPx__NOT_DOOR_OPEN								83
#define  ALID__LPx__FOUP_NOT_EXIST								84
#define  ALID__LPx__FOUP_NOT_CLAMP								85
#define  ALID__LPx__FOUP_NOT_LOAD								86
#define  ALID__INTLK__EFEM_DOOR_NOT_CLOSE						87
#define  ALID__INTLK__LPx_CANNOT_MAP_WAFER_EXIST_ON_ARM			88

#define  ALID__ATM_RB_HAS_NO_MAPPING_SENSOR          			89

