#pragma once


// ...
#define  ACT__RETRY									"RETRY"
#define  ACT__ABORT									"ABORT"
#define  ACT__CLEAR									"CLEAR"
#define  ACT__CHECK									"CHECK"

// ...
#define  ALID__VAT__CONTROL_WARNING_RANGE				1
#define  ALID__VAT__CONTROL_ABORT_RANGE					2
#define  ALID__VAT__CONTROL_IDLE_WARNING_RANGE			3
#define  ALID__VAT__CONTROL_IDLE_ABORT_RANGE			4

#define  ALID__TRANSFER_BALLAST_PRESSURE_WAIT			5
#define  ALID__TRANSFER_BALLAST_OVER_PRESSURE			6

#define  ALID__CHAMBER_BALLAST_PRESSURE_WAIT			7
#define  ALID__CHAMBER_BALLAST_OVER_PRESSURE			8

#define  ALID__VAT_CONTROL_ABORTED						11
#define  ALID__VAT_NOT_USE								12
#define  ALID__TV_INTERLOCK_STATE						13

#define  ALID__VAT_OPEN_TIMEOUT							15
#define  ALID__VAT_CLOSE_TIMEOUT						16

#define  ALID__VAT_ENABLE_SENSOR_ERROR					21
#define  ALID__VAT_READY_ERROR							22

#define  ALID__OPEN_INTERLOCK_OVER_PRESSURE				25
