#pragma once


// ...
#define APC_CMMD__CLOSE				"CLOSE"
#define APC_CMMD__OPEN				"OPEN"
#define APC_CMMD__POSITION			"POSITION"

#define APC_CMMD__BALLAST_CTRL		"BALLAST_CTRL"
#define APC_CMMD__BALLAST_POS		"BALLAST_POS"

// ...
#define PMP_CMMD__ALL_CLOSE			"ALL_CLOSE"

#define PMP_CMMD__FR_CLOSE			"FR_CLOSE"
#define PMP_CMMD__FR_OPEN			"FR_OPEN"

#define PMP_CMMD__SR_CLOSE			"SR_CLOSE"
#define PMP_CMMD__SR_OPEN			"SR_OPEN"

#define PMP_CMMD__EXHAUST_CLOSE		"EXHAUST_CLOSE"
#define PMP_CMMD__EXHAUST_OPEN		"EXHAUST_OPEN"
