#pragma once


// ...
#define  ALID__SIMULATION_MODE_ACTIVE							1

#define ALID__SETPOINT_INTERLOCK__DISABLE						2
#define ALID__SETPOINT_AND_MONITORING_INTERLOCK__DISABLE		3


// ...
#define STR__DISABLE					"DISABLE"
#define STR__ENABLE						"ENABLE"

#define STR__ALL_DISABLE				"ALL_DISABLE"


// ...
#define CFG_INTERLOCK__LIMIT			30
#define CFG_INTERLOCK__MFC_SIZE			5

#define CFG_SIZE__MFC_OBJ				17

#define CFG_SIZE__LOG_LEAKCHECK			10

