#pragma once


// ..
#define  ACT__RETRY									"RETRY"
#define  ACT__ABORT									"ABORT"


// ..
#define  ALID__DOOR_VALVE_OPEN__TIMEOUT					1
#define  ALID__DOOR_VALVE_CLOSE__TIMEOUT				2
#define  ALID__SLIT_VALVE_OPEN__TIMEOUT					3
#define  ALID__SLIT_VALVE_CLOSE__TIMEOUT				4
#define  ALID__SLIT_CANNOT_CLOSE_NOT_EXIST				5
#define  ALID__SLIT_CANNOT_OPEN_NOT_EXIST				6
#define  ALID__MAX_DIFFER_PRESS_ALARM					7
#define  ALID__CONVECTRON_ATM_HIGH_PRESS_ALARM			8

#define  ALID__SV_OPEN__NOT_ATM_ERROR					11
#define  ALID__SV_OPEN__NOT_VAC_ERROR					12
#define  ALID__DV_OPEN__NOT_ATM_ERROR					13

#define  ALID__SOFT_PUMPING__TIMEOUT					14
#define  ALID__FAST_PUMPING__TIMEOUT					15

#define  ALID__SOFT_VENTING__TIMEOUT					16
#define  ALID__FAST_VENTING__TIMEOUT					17

#define  ALID__VENT_VALVE__PUMP_INTERLOCK				21
#define  ALID__DOOR_VALVE__PUMP_INTERLOCK				22

#define  ALID__DOOR_VALVE__NOT_CLOSE					23
#define  ALID__SLIT_VALVE__NOT_CLOSE					24

#define  ALID__PUMP_OFFLINE_OFF_INTERLOCK               25
#define  ALID__VAC_RB_NOT_RETRACTED                     26
#define  ALID__ATM_RB_NOT_RETRACTED                     27
