#pragma once


#define STR_STANDBY					"STANDBY"
#define STR_MAINTMODE				"MAINTMODE"

#define STR_APC_VALUE_CONTROL		"APC_VALUE_CONTROL"
#define STR_N2_FLOW_START			"N2_FLOW_START"
#define STR_N2_FLOW_STOP			"N2_FLOW_STOP"
#define STR_AR_FLOW_START			"AR_FLOW_START"
#define STR_AR_FLOW_STOP			"AR_FLOW_STOP"
