#pragma once


// ...
#define ALID__PROCESS_RECIPE_NOT_EXIST				11
#define ALID__PROCESS_RECOVERY_CHECK				12
#define ALID__PLSAMA_DECHUCK_RECIPE_NOT_EXIST		13
#define ALID__PLSAMA_DECHUCK_PROCESS_FAILED			14

#define ALID__PROCESS_RECIPE_FILE_CHANGING_NOW		15

#define ALID__WAFER_STATUS_CONVERT_TO_PROCESSED     16
#define ALID__WAFER_ALREADY_PROCESSED				17

#define ALID__RECIPE_STEP_SIZE_ERROR				18

#define ALID__PROCESS_NOT_READY						19
