#pragma once


// ...
#define ALID__PROCESS_STEP_OVERTIME							2
#define ALID__PROCESS_STABLE_OVERTIME						3
#define ALID__PROCESS_OVERETCH_OVERTIME						4
#define ALID__PROCESS_CH_INTERLOCK_ALARM					5
#define ALID__RECIPE_OES_DATA_NULL_ERROR					6

#define ALID__SYSTEM_INTERLOCK_SENSOR_ERROR					7
#define ALID__MFC_INTERLOCK_CLOSE_ERROR						8
#define ALID__PROCESS_RECIPE_FILE_CHANGING_NOW				9

#define ALID__GAS_FLOW_TOLERANCE_WARNING					11		// ~ 30
#define ALID__GAS_FLOW_TOLERANCE_FAULT						31		// ~ 50

#define ALID__CHM_PRESSURE_TOLERANCE_WARNING				51		
#define ALID__CHM_PRESSURE_TOLERANCE_FAULT					52		

#define ALID__RF_BIAS__TOLERANCE_WARNING					55		
#define ALID__RF_BIAS__TOLERANCE_FAULT						56		


#define ALID__MIDDLE_PIN_UP_TIMEOUT							68


// Temperature Tolerance ...
// ...
#define ALID__ALL_TEMP__HEADER_READY_CHECK					69
#define ALID__ALL_TEMP__HEADER_READY_COMPLETE				70

//
#define ALID__TOP_TEMP__HEADER_TOLERANCE_WARNING			71
#define ALID__TOP_TEMP__HEADER_TOLERANCE_FAULT				72

#define ALID__BOTTOM_TEMP__HEADER_TOLERANCE_WARNING			73
#define ALID__BOTTOM_TEMP__HEADER_TOLERANCE_FAULT			74

#define ALID__TOP_PLATE__HEADER_TOLERANCE_WARNING			75
#define ALID__TOP_PLATE__HEADER_TOLERANCE_FAULT				76

//
#define ALID__TOP_TEMP__HEADER_LOW_LIMIT					81
#define ALID__TOP_TEMP__HEADER_HIGH_LIMIT					82

#define ALID__BOTTOM_TEMP__HEADER_LOW_LIMIT					83
#define ALID__BOTTOM_TEMP__HEADER_HIGH_LIMIT				84

#define ALID__TOP_PLATE__HEADER_LOW_LIMIT					85
#define ALID__TOP_PLATE__HEADER_HIGH_LIMIT					86

//
#define ALID__TCU__ERROR_SENSOR_DETECTED					87
#define ALID__TCU__WARNING_SENSOR_DETECTED					88

#define ALID__GAS_BOX__ERROR_SENSOR_DETECTED				89

// ...
#define ALID__HE_DECHUCK__TIMEOUT							91
#define ALID__HE_DECHUCK__INIT_ERROR						92

// ...
#define ALID__WAP_CONDUCTANCE__NOT_CHECK					93
#define ALID__CHAMBER_LID__OPEN								94


// ...
#define ALID__SYSTEM_INTERLOCK_OCCUR						100

// ...
#define ALID__ALL_TEMP__STEP_READY_CHECK					101
#define ALID__ALL_TEMP__STEP_READY_COMPLETE					102

//
#define ALID__TOP_TEMP__STEP_TOLERANCE_WARNING				103
#define ALID__TOP_TEMP__STEP_TOLERANCE_FAULT				104

#define ALID__BOTTOM_TEMP__STEP_TOLERANCE_WARNING			105
#define ALID__BOTTOM_TEMP__STEP_TOLERANCE_FAULT				106

#define ALID__TOP_PLATE__STEP_TOLERANCE_WARNING				107
#define ALID__TOP_PLATE__STEP_TOLERANCE_FAULT				108

//
#define ALID__TOP_TEMP__STEP_LOW_LIMIT						110
#define ALID__TOP_TEMP__STEP_HIGH_LIMIT						111

#define ALID__BOTTOM_TEMP__STEP_LOW_LIMIT					112
#define ALID__BOTTOM_TEMP__STEP_HIGH_LIMIT					113

#define ALID__TOP_PLATE__STEP_LOW_LIMIT						114
#define ALID__TOP_PLATE__STEP_HIGH_LIMIT					115

//
#define ALID__STEP_TEMP_CTRL_ABORTED						116

//
#define ALID__PROC_RESTART_SYSTEM_INIT_ERROR				121
#define ALID__WAP_MOVING_COMPLETE__TIMEOUT                  122

