#pragma once

#include "Interface_Code.h"

#include "CCommon_Error.h"
#include "Ccommon_Def.h"


class CObj__PROC_FNC : public __IOBJ__STD_TYPE
{
private:
	//-------------------------------------------------------------------------
	CString sObject_Name;

	// ...
	CCommon_Error__DEF_VARIABLE mERROR__DEF_VAR;
	CCommon_Error__USER_FNC     mERROR__USER_FNC;

	SCX__USER_LOG_CTRL xLOG_CTRL;

	SCX__RECIPE_FILE xRCP_FILE;
	SCX__RECIPE_FILE xRCP_FILE_PLASMA_DECHUCK;

	// ...
	int iActive__SIM_MODE;

	SCX__ASYNC_TIMER_CTRL xTIMER_ASYNC;
	CString sDIR_PROC;
	//


	//-------------------------------------------------------------------------
	//  INTERNAL PROPERTY

	// ...
	CX__VAR_STRING_CTRL	 sCH__OBJ_MSG;
	CX__VAR_STRING_CTRL  sCH__CFG_PLASMA_DECHUCK_RCP_NAME;
	CX__VAR_DIGITAL_CTRL dCH__DATALOG_GATHERING_ENABLE_DISABLE;

	CX__VAR_STRING_CTRL  xCH__PRC_TOTAL_TIME_TO_CTC;
	CX__VAR_STRING_CTRL  xCH__PRC_CHANGE_TIME_TO_CTC;

	CX__VAR_STRING_CTRL  xCH__PRC_TOTAL_TIME;
	CX__VAR_STRING_CTRL  xCH__PRC_CUR_TIME;

	CX__VAR_ANALOG_CTRL  xCH__STEP_TOTAL_NUM;
	CX__VAR_ANALOG_CTRL  xCH__STEP_CUR_NUM;
	CX__VAR_STRING_CTRL  xCH__LAST_STEP_FLAG;

	CX__VAR_STRING_CTRL  xCH__LOOP_MSG;

	CX__VAR_STRING_CTRL  sCH__PARA_PROCESS_TYPE;

	// ...
	CX__VAR_STRING_CTRL  sCH__REPORT_TOTAL_ERROR_SEC;
	CX__VAR_STRING_CTRL  sCH__REPORT_AVG_ERROR_SEC;

	// ...
	CX__VAR_ANALOG_CTRL  aCH__SVID_PROCESS_STATE;
	CX__VAR_ANALOG_CTRL  aCH__SVID_CLEAN_COUNT;

	CX__VAR_STRING_CTRL  xCH__PRC_STS;
	CX__VAR_STRING_CTRL  xCH__CHM_STATE;

	CX__VAR_STRING_CTRL  sCH__RCP_FILE_UPLOAD_FLAG;

	CX__VAR_STRING_CTRL  sCH__ACT_RECOVERY_RESTART_FLAG;

	//
	CX__VAR_STRING_CTRL  sCH__NEXT_STEP_CTRL_FLAG;
	CX__VAR_STRING_CTRL  sCH__NEXT_STEP_CTRL_REQ;

	//
	CX__VAR_STRING_CTRL  sCH__PROCESS_STATUS_FLAG;

	//
	CX__VAR_STRING_CTRL  sCH__PMC_RECV_APC_APPLY;
	CX__VAR_STRING_CTRL  sCH__PMC_RECV_APC_DATA;

	// ...
	int iPROC_START_FLAG;

	CX__VAR_STRING_CTRL  sCH__LOCK_FLAG__ABORT;
	CX__VAR_STRING_CTRL  sCH__LOCK_FLAG__END;
	CX__VAR_STRING_CTRL  sCH__LOCK_FLAG__SKIP;
	CX__VAR_STRING_CTRL  sCH__LOCK_FLAG__JUMP;
	CX__VAR_STRING_CTRL  sCH__LOCK_FLAG__PAUSE;
	CX__VAR_STRING_CTRL  sCH__LOCK_FLAG__RESUME;

	CX__VAR_STRING_CTRL  sCH__EXCEPTION_ACT;
	CX__VAR_STRING_CTRL  sCH__EXCEPTION_LAST_ACT;
	CX__VAR_STRING_CTRL  sCH__EXCEPTION_MSG;

	//
	CX__VAR_ANALOG_CTRL  aCH__JUMP_STEP_ID;
	CX__VAR_ANALOG_CTRL  aCH__CONTINUE_OVER_STEP_TIME;

	CX__VAR_STRING_CTRL  sCH__WIN_CTRL_JUMP_PAGE;
	CX__VAR_STRING_CTRL  sCH__WIN_CTRL_LOCK;
	CX__VAR_STRING_CTRL  sCH__WIN_CTRL_MSG;

	//
	CX__VAR_STRING_CTRL  sCH__PRC_REAL_CHART_START;	

	CX__VAR_STRING_CTRL  sCH__WAFER_STATUS_CONVERTED_TO_PROCESSED_BY_PMC_REQ_COUNT;
	//


	//-------------------------------------------------------------------------
	//  EXTERNAL PROPERTY

	// OBJ  DB_INF
	CX__VAR_STRING_CTRL  sEXT_CH__RCP_NAME;

	CX__VAR_STRING_CTRL  sEXT_CH__PRC_TOTAL_TIME_TO_CTC;
	CX__VAR_STRING_CTRL  sEXT_CH__PRC_CHANGE_TIME_TO_CTC;

	CX__VAR_DIGITAL_CTRL dEXT_CH__SLOT01_STATUS;
	CX__VAR_STRING_CTRL  sEXT_CH__SLOT01_TITLE;

	CX__VAR_STRING_CTRL  sEXT_CH__SLOT01_LOTID;
	CX__VAR_STRING_CTRL  sEXT_CH__SLOT01_MATERIALID;
	CX__VAR_STRING_CTRL  sEXT_CH__SLOT01_PORTID;
	CX__VAR_STRING_CTRL  sEXT_CH__SLOT01_SLOTID;	

	CX__VAR_DIGITAL_CTRL dEXT_CH__CFG_DECHUCK_CTRL_MODE;
	CX__VAR_STRING_CTRL  sEXT_CH__CFG_DECHUCK_RECIPE_ABORT;

	// OBJ  DB_SYS
	CX__VAR_STRING_CTRL  sEXT_CH__MON_SYSTEM_PROCESS_ACTIVE;
	CX__VAR_STRING_CTRL  sEXT_CH__SYSTEM_PROCESS_STEP_ID;
	CX__VAR_STRING_CTRL  sEXT_CH__SYSTEM_PROCESS_LAST_STEP_FLAG;


	// OBJ  OPR
	CX__VAR_DIGITAL_CTRL dEXT_CH__SYSTEM_OBJ_STATUS;


	// OBJ  CHM
	CII_EXT_OBJECT__CTRL *pOBJ_CTRL__CHM;


	// OBJ  DATALOG
	CString sEXT_MODE__LOG_ENABLE;
	CString sEXT_MODE__LOG_DISABLE;

	CString sEXT_MODE__LOG_PAUSE;
	CString sEXT_MODE__LOG_RESUME;

	CString sEXT_MODE__LOG_STEP_START;
	CString sEXT_MODE__LOG_STEP_END;
	CString sEXT_MODE__LOG_STEP_END_START;
	CString sEXT_MODE__LOG_STEP_ABORT;

	CX__VAR_STRING_CTRL xEXT_CH__LOG_LOTID;
	CX__VAR_STRING_CTRL xEXT_CH__LOG_RECIPEID;
	CX__VAR_STRING_CTRL xEXT_CH__LOG_PORTID;
	CX__VAR_STRING_CTRL xEXT_CH__LOG_SLOTID;

	CX__VAR_STRING_CTRL xEXT_CH__LOG_SUB_DIR;
	CX__VAR_STRING_CTRL xEXT_CH__LOG_FILE_NAME;	


	// Step Control .....
	CString sEXT_MODE__STEP_READY;
	CString sEXT_MODE__STEP_START;
	CString sEXT_MODE__STEP_PROC;
	CString sEXT_MODE__STEP_ABORT;
	CString sEXT_MODE__STEP_END;

	CX__VAR_DIGITAL_CTRL dRCP_CH__PROCESS_DATA_SUMMARY;


	// Channel Link .....
	// OBJ STEP 
	CII_EXT_OBJECT__CTRL *pOBJ__STEP_CTRL;

	CX__VAR_STRING_CTRL  xEXT_CH__CUR_PROC_TYPE;
	CX__VAR_STRING_CTRL  sEXT_CH__RCP_FILE_PATH;

	CX__VAR_ANALOG_CTRL  aEXT_CH__RCP__LOOP_START;
	CX__VAR_ANALOG_CTRL  aEXT_CH__RCP__LOOP_REPEAT;

	// 
	CX__VAR_ANALOG_CTRL  aEXT_CH__STEP_TIME;
	CX__VAR_STRING_CTRL  sEXT_CH__STEP_EXCEPTION_COMMAND;
	CX__VAR_STRING_CTRL  sEXT_CH__STEP_STABLE_REQ;

	//
	CX__VAR_STRING_CTRL  sEXT_CH__EXCEPTION_CONTINUE_REQ;
	CX__VAR_STRING_CTRL  sEXT_CH__EXCEPTION_CONTINUE_STEP_OVER_TIME;

	CX__VAR_STRING_CTRL  sEXT_CH__SLOT_TITLE;
	CX__VAR_STRING_CTRL  sEXT_CH__SLOT_LOTID;

	CX__VAR_STRING_CTRL  sEXT_CH__SYS_CTRL_LOCK;
	CX__VAR_STRING_CTRL  sEXT_CH__SYS_FNC_LOCK;
	CX__VAR_DIGITAL_CTRL dEXT_CH__SYS_STATUS;

	//
	CX__VAR_STRING_CTRL  sEXT_CH__SHUTTER_STATE;
	CX__VAR_STRING_CTRL  sEXT_CH__LIFT_PIN_STATE;
	CX__VAR_STRING_CTRL  sEXT_CH__CHUCK_STATE;
	//


	//-------------------------------------------------------------------------
	// ...
	CString sMODE__INIT;
	int  Call__INIT(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	// ...
	CString sMODE__PROC_READY;
	int  Call__PROC_READY(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);
	int  Fnc__PROC_READY(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	CString sMODE__PROC_START;
	int  Call__PROC_START(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);
	int  Fnc__PROC_START(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);
	int  _Fnc__PROC_START(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);
	int  Fnc__PROC_STEP_START(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	// ...
	int  Fnc__PLASMA_DECHUCK_START(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);
	int  Fnc__PROC_PLASMA_DECHUCK_START(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	// ...
	CString sMODE__CLN_READY;
	int Call__CLN_READY(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	CString sMODE__CLN_START;
	int Call__CLN_START(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	CString sMODE__MNT_READY;
	int Call__MNT_READY(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	CString sMODE__MNT_START;
	int Call__MNT_START(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	CString sMODE__JOB_STRT_READY;
	int Call__JOB_START_READY(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);

	CString sMODE__JOB_END_READY;
	int Call__JOB_END_READY(CII_OBJECT__VARIABLE* p_variable,CII_OBJECT__ALARM* p_alarm);
	//

	// ...
	void Mon__PROC_EXCEPTION_CTRL(const int event_id, CII_OBJECT__VARIABLE *p_variable,CII_OBJECT__ALARM *p_alarm);
	void Mon__SYSTEM_LOCK_CTRL(const int event_id, CII_OBJECT__VARIABLE *p_variable,CII_OBJECT__ALARM *p_alarm);

	// ...
	int  Fnc__PRC_LOG__ENABLE(CII_OBJECT__VARIABLE *p_variable);
	int  Fnc__PRC_LOG__DISABLE(CII_OBJECT__VARIABLE *p_variable);
	int  Fnc__PRC_LOG__PAUSE(CII_OBJECT__VARIABLE *p_variable);
	int  Fnc__PRC_LOG__RESUME(CII_OBJECT__VARIABLE *p_variable);
	//


public:
	CObj__PROC_FNC();
	~CObj__PROC_FNC();

	//-------------------------------------------------------------------------
	int __DEFINE__CONTROL_MODE(obj,l_mode);
	int __DEFINE__VERSION_HISTORY(version);
	
	int __DEFINE__VARIABLE_STD(p_variable);
	int __DEFINE__ALARM(p_alarm);

	int __Define__USER_FUNCTION(CII_DEFINE__FUNCTION *p_fnc_ctrl);

	//-------------------------------------------------------------------------
	int __INITIALIZE__OBJECT(p_variable,p_ext_obj_create);

	//-------------------------------------------------------------------------
	int __CALL__CONTROL_MODE(mode,p_debug,p_variable,p_alarm);
	int __CALL__MONITORING(id,p_variable,p_alarm);
};
