#pragma once


// ...
enum { MODE__DRY_PUMP_ON, MODE__DRY_PUMP_OFF, MODE__TMP_ON, MODE__TMP_OFF };


// ...
#define CMMD__PHY_APC__GOTO_POSITION		"GOTO_POSITION"

// ...
#define CMMD_GAS__ALL_CLOSE					"ALL_CLOSE"
#define CMMD_GAS__PROC_READY				"PROC_READY"
#define CMMD_GAS__FV_OPEN					"FV_OPEN"
#define CMMD_GAS__FV_CLOSE					"FV_CLOSE"
#define CMMD_GAS__SV_OPEN					"SV_OPEN"
#define CMMD_GAS__SV_CLOSE					"SV_CLOSE"

// ...
#define CMMD_FRC__CONTROL					"CONTROL"

// ...
#define CMMD_VAC__ALL_CLOSE					"ALL_CLOSE"
#define CMMD_VAC__SR_OPEN					"SR_OPEN"
#define CMMD_VAC__FR_OPEN					"FR_OPEN"
#define CMMD_VAC__SR_CLOSE					"SR_CLOSE"
#define CMMD_VAC__FR_CLOSE					"FR_CLOSE"
#define CMMD_VAC__EXHAUST_OPEN  			"EXHAUST_OPEN"
#define CMMD_VAC__EXHAUST_CLOSE				"EXHAUST_CLOSE"

// ...
#define CMMD_TMP__FULL_OPEN					"FULL_OPEN"
#define CMMD_TMP__FULL_CLOSE				"FULL_CLOSE"

#define CMMD_TMP__EXHAUST_OPEN				"EXHAUST_OPEN"
#define CMMD_TMP__EXHAUST_CLOSE				"EXHAUST_CLOSE"

#define CMMD_TMP__PUMP_ON					"ON"
#define CMMD_TMP__PUMP_OFF					"OFF"
#define CMMD_TMP__PUMP_OFF_NO_WAIT			"OFF_NO_WAIT"

// ...
#define _APC_CMMD__OPEN						"OPEN"
#define _APC_CMMD__CLOSE					"CLOSE"
#define _APC_CMMD__POSITION					"POSITION"

#define	_APC_CMMD__BALLAST_TRANSFER			"BALLAST.TRANSFER"
#define	_APC_CMMD__BALLAST_CHAMBER			"BALLAST.CHAMBER"

#define _APC_CMMD__AUTO_LEARN				"AUTO_LEARN"

// ...
#define _ESC_CMMD__PUMP_READY				"PUMP.READY"
#define _ESC_CMMD__VENT_READY				"VENT.READY"

#define _ESC_CMMD__DECHUCK					"DECHUCK"

// ...
#define CMMD__CHM_BALLAST_FLOW				"CHM_BALLAST_FLOW"
#define CMMD__TRANS_BALLAST_FLOW			"TRANS_BALLAST_FLOW"
#define CMMD__BALLAST_CLOSE					"BALLAST_CLOSE"

// ...
#define CMMD__LOG_ENABLE_TIME				"ENABLE_TIME"
#define CMMD__LOG_ENABLE					"ENABLE"
#define CMMD__LOG_DISABLE					"DISABLE"
#define CMMD__LOG_PAUSE        				"PAUSE"
#define CMMD__LOG_RESUME					"RESUME"
#define CMMD__LOG_STEP_START				"STEP_START"
#define CMMD__LOG_STEP_END					"STEP_END"
#define CMMD__LOG_STEP_ABORT				"STEP_ABORT"

// ...
#define CMMD__EXHAUST_OPEN					"EXHAUST_OPEN"
#define CMMD__EXHAUST_CLOSE					"EXHAUST_CLOSE"

