#pragma once


// ...
#define  ACT__RETRY							"RETRY"
#define  ACT__ABORT							"ABORT"
#define  ACT__IGNORE						"IGNORE"


// ...
#define  ALID__ATM_TIMEOUT													1
#define  ALID__SOFT_VENT_TIMEOUT											2
#define  ALID__SOFT_PUMP_TIMEOUT											3
#define  ALID__LOW_VAC_TIMEOUT												4
#define  ALID__HIGH_VAC_TIMEOUT												5
#define  ALID__FORELINE_PUMP_TIMEOUT										6
#define  ALID__FORELINE_OVER_PUMP_DELAY										7
#define  ALID__FORELINE_SENSOR_AND_VALUE_CHECK_TIMEOUT						8
#define	 ALID__PREPARE_FAST_PUMP_TIMEOUT									9
#define  ALID__LOW_VAC_CHECK_COMPLETE_TIMEOUT								10
#define  ALID__HI_VAC_CHECK_COMPLETE_TIMEOUT								11
#define	 ALID__VENT_CHECK_COMPLETE_TIMEOUT									12	
#define  ALID__CHM_SLOT_VALVE_NOT_CLOSE										13
#define  ALID__RF_CONTACT_ENABLE_TIMEOUT									14
#define  ALID__APC_VALVE_CLOSE_CONDITION_OCCUR								15
#define  ALID__MANO_ISO_VALVE_CLOSE_CONDITION_OCCUR							16

#define  ALID__VACUUM_SNS_OFF_TIMEOUT										18
#define  ALID__ATM_SNS_ON_TIMEOUT											19
#define  ALID__LEAK_CHECK_MAX_PRESSURE_ALARM								20
#define  ALID__LEAK_CHECK_RESULT_ALARM										21
#define  ALID__MAIN_WATER_LEAK_DETECT_ALARM									22
#define  ALID__RF_CONTACT_OFF_CONDITION__RF_MATCHER_OFFLINE_ALARM			23
#define  ALID__RF_CONTACT_OFF_CONDITION__NOT_VAC_STS_ALARM					24
#define  ALID__RF_CONTACT_OFF_CONDITION__DRYPUMP_POWER_STS_ALARM			25
#define  ALID__RF_CONTACT_OFF_CONDITION__RF_MATCHER_NOT_NORMAL_ALARM		26
#define  ALID__VAC_SENSOR_CHECKING_TIMEOUT									27

#define  ALID__DRY_PUMP_STATE_NOT_ON										29
#define  ALID__SHUTTER_VALVE_NOT_CLOSE										30

#define  ALID__PLATE_TEMP_INTERLOCK_FOR_VENTING								32
#define  ALID__PMC_STATUS__ATM_MAINT										33

#define  ALID__LEAK_CHECK__VAT_MOVE__START_PRESSURE_OVER					34

