#pragma once


#define  ALID__OBJECT_MODE_UNKNOWN									11

#define  ALID__JOB_ERROR__ATM_RB__NOT_STANDBY						12
#define  ALID__JOB_ERROR__AL1__NOT_STANDBY							13

#define  ALID__JOB_ERROR__LBA__NOT_STANDBY							15
#define  ALID__JOB_ERROR__LBB__NOT_STANDBY							16
#define  ALID__JOB_ERROR__LBA__CHECK_ATM_PRESSURE					17
#define  ALID__JOB_ERROR__LBB__CHECK_ATM_PRESSURE					18
#define  ALID__JOB_ERROR__WAFER_INFO_MISMATCH						19

#define  ALID__MANUAL_MOVE__MODULE_STATUS_ERROR						21
#define  ALID__TOOL_CLEAR__MODULE_STATUS_ERROR						22

#define  ALID__MOVE_ERROR__WAFER_CONFIRM							25
#define  ALID__USER_CHECK__WAFER_CONFIRM							26
#define  ALID__PICK_ERROR__WAFER_MITMATCH							27
#define  ALID__PLACE_ERROR__WAFER_MITMATCH							28

#define  ALID__LBx_CONFIG_ERROR										31
#define  ALID__BUFFERx_CONFIG_ERROR									32

#define  ALID__SWAP_ERROR											35

#define  ALID__MANUAL_MOVE__ACTION_ERROR							36
#define  ALID__TOOL_CLEAR__ACTION_ERROR								37

#define  ALID__LLx_STATUS__IS_NOT_AVAILABLE							41

#define  ALID__LPx_STATUS__IS_NOT_AVAILABLE							43
#define  ALID__LPx_MATERIAL_PICK__JOB_ERROR							44
#define  ALID__LPx_MATERIAL_PLACE__JOB_ERROR						45
#define  ALID__LPx__MAP_ABORTED										46

#define  ALID__ALx_LLx_TARGET_NAME_ERROR							47
#define  ALID__ATM_ROBOT__MOVE_PAUSED								48

#define  ALID__MAINT_PICK_ERROR__ATM_RB_PAUSED						49
#define  ALID__MAINT_PLACE_ERROR__ATM_RB_PAUSED						50
