PHY_MFC1+MON.MFC.READ.FLOW 
PHY_MFC1+MON.MFC.SET.FLOW 
PHY_MFC2+MON.MFC.READ.FLOW 
PHY_MFC2+MON.MFC.SET.FLOW 
PHY_FRC1+MON.CH2.GET_RATIO 
PHY_FRC1+MON.CH1.GET_RATIO 
PHY_FRC2+MON.CH1.GET_RATIO 
PHY_FRC2+MON.CH2.GET_RATIO 
