#pragma once


// ...
#define ACT__CLEAR							"CLEAR"


// ...
#define ALID__STEP_OVERTIME											1
#define ALID__STABLE_OVERTIME										2
#define ALID__OBJECT_OVERTIME										3

#define ALID__STEP_READY__TEMPERATURE_STABLE_TIMEOUT_ERROR			4
#define ALID__STEP_READY__TEMPERATURE_STABLE_TIMEOUT_WARNING		5

#define ALID__STEP_PARAMETER__SETTING_ERROR							6
