#pragma once


// ...
#define pKEY__DATA_CONFIG_PATH				"DATA.CONFIG_PATH"
#define pKEY__DATA_CONFIG_DIR				"DATA.CONFIG_DIR";
#define pKEY__DATA_CONFIG_FILE				"DATA.CONFIG_FILE"
#define pKEY__DATA_GROUP_USE				"DATA.GROUP_USE"
#define pKEY__DATA_GROUP_LIST				"DATA.GROUP_LIST"
