#pragma once


#define  ERROR_CODE__NO_ERROR								0
#define  ERROR_CODE__UNKNOWN_OBJECT_IN_OBJECT_SPECIFIER					1
#define  ERROR_CODE__UNKNOWN_TARGET_OBJECT_TYPE						2
#define  ERROR_CODE__UNKNOWN_OBJECT_INSTANCE						3
#define  ERROR_CODE__UNKNOWN_ATTRIBUTE_NAME						4
#define  ERROR_CODE__READ_ONLY_ATTRIBUTE						5
#define  ERROR_CODE__UNKNOWN_OBJECT_TYPE						6
#define  ERROR_CODE__INVALID_ATTRIBUTE_VALUE						7
#define  ERROR_CODE__SYNTAX_ERROR							8
#define  ERROR_CODE__VERIFICATION_ERROR							9
#define  ERROR_CODE__VALIDATION_ERROR							10
#define  ERROR_CODE__OBJECT_IDENTIFIER_IN_USE						11
#define  ERROR_CODE__PARAMETER_IMPROPERLY_SPECIFIED					12
#define  ERROR_CODE__INSUFFICIENT_PARAMETERS_SPECIFIED					13
#define  ERROR_CODE__UNSUPPORTED_OPTION_REQUESTED					14
#define  ERROR_CODE__BUSY								15
#define  ERROR_CODE__NOT_AVAILABLE_FOR_PROCESSING					16
#define  ERROR_CODE__COMMAND_NOT_VALID_FOR_CURRENT_STATE				17
#define  ERROR_CODE__NO_MATERIAL_ALTERED						18
#define  ERROR_CODE__MATERIAL_PARTIALLY_PROCESSED					19
#define  ERROR_CODE__ALL_MATERIAL_PROCESSED						20
#define  ERROR_CODE__RECIPE_SPECIFICATION_RELATED_ERROR					21
#define  ERROR_CODE__FAILED_DURING_PROCESSING						22
#define  ERROR_CODE__FAILED_WHILE_NOT_PROCESSING					23
#define  ERROR_CODE__FAILED_DUE_TO_LACK_OF_MATERIAL					24
#define  ERROR_CODE__JOB_ABORTED							25
#define  ERROR_CODE__JOB_STOPPED							26
#define  ERROR_CODE__JOB_CANCELLED							27
#define  ERROR_CODE__CANNOT_CHANGE_SELECTED_RECIPE					28
#define  ERROR_CODE__UNKNOWN_EVENT							29
#define  ERROR_CODE__DUPLICATE_REPORT_ID						30
#define  ERROR_CODE__UNKNOWN_DATA_REPORT						31
#define  ERROR_CODE__DATA_REPORT_NOT_LINKED						32
#define  ERROR_CODE__UNKNOWN_TRACE_REPORT						33
#define  ERROR_CODE__DUPLICATE_TRACE_ID							34
#define  ERROR_CODE__TOO_MANY_DATA_REPORTS						35 
#define  ERROR_CODE__SAMPLE_PERIOD_OUT_OF_RANGE						36
#define  ERROR_CODE__GROUP_SIZE_TO_LARGE						37
#define  ERROR_CODE__RECOVERY_ACTION_CURRENTLY_INVALID					38
#define  ERROR_CODE__BUSY_WITH_ANOTHER_RECOVERY						39
#define  ERROR_CODE__NO_ACTIVE_RECOVERY_ACTION						40
#define  ERROR_CODE__EXCEPTION_RECOVERY_FAILED						41
#define  ERROR_CODE__EXCEPTION_RECOVERY_ABORTED						42
#define  ERROR_CODE__INVALID_TABLE_ELEMENT						43
#define  ERROR_CODE__UNKNOWN_TABLE_ELEMENT						44
#define  ERROR_CODE__CANNOT_DELETE_PREDEFINED						45
#define  ERROR_CODE__INVALID_TOKEN							46
#define  ERROR_CODE__INVALID_PARAMTER							47
#define  ERROR_CODE__LOAD_PORT_DOES_NOT_EXIST						48
#define  ERROR_CODE__LOAD_PORT_ALREADY_IN_USE						49
#define  ERROR_CODE__MISSING_CARRIER							50
#define  ERROR_CODE__THERE_IS_NO_CJOB_IN_QUEUE						51
#define  ERROR_CODE__CSTID_IS_USING_IN_OTHER_CJOBID					52
#define  ERROR_CODE__CSTID_DOES_NOT_EXIST						53

#define  ERROR_CODE__CJOB_NAME_ERROR							54
#define  ERROR_CODE__PJOB_NAME_ERROR							55
#define  ERROR_CODE__CSTID_NAME_ERROR							56

#define  ERROR_CODE__NO_SLOT_MAP_INFO							63

#define  ERROR_CODE__DUPLICATE_CARRIERID						64
#define  ERROR_CODE__DUPLICATE_SLOTID							65

