#pragma once


// ...
#define ACT__CLEAR										"CLEAR"
#define ACT__CHECK										"CHECK"


// ...
#define ALID__PART_NOT_USE								1
#define ALID__PART_CTRL_ABORTED							2

#define ALID__FORWARD_POWER__PROCESS_WARNING_RANGE		3
#define ALID__FORWARD_POWER__PROCESS_ABORT_RANGE		4
#define ALID__FORWARD_POWER__IDLE_WARNING_RANGE			5
#define ALID__FORWARD_POWER__IDLE_ABORT_RANGE			6

#define ALID__VACUUM_SWITCH_ALARM						11
#define ALID__ATM_SWITCH_ALARM							12
#define ALID__CHAMBER_LID_INTLK_ALARM					13
#define ALID__CHAMBER_SHUTTER_NOT_CLOSE  				14
#define ALID__INTERLOCK_SENSOR_ALARM					15

#define ALID__REFLECTED_POWER_OVER						21
#define ALID__REFLECTED_COEFF_OVER						22

#define ALID__REFLECTED_POWER_WARNING					24
#define ALID__REFLECTED_POWER_ALARM						25
#define ALID__RF_MAX_POWER_OVER_WHITOUT_WAFER			26

#define ALID__RF_MAX_ALLOWED_POWER_OVER					27

