#pragma once


// ...
#define  ALID__ESC_CHUCK_STATUS__UNKNOWN							1
#define  ALID__ESC_CHUCK_ERROR__PRESSURE_NOT_VAC					2
#define  ALID__ESC_CHUCK_ERROR__WAFER_NOT_EXIST						3

#define  ALID__ESC_CENTER_CHUCK_VOLTAGE__MIN_ERROR					4
#define  ALID__ESC_CENTER_CHUCK_VOLTAGE__MAX_ERROR					5
#define  ALID__ESC_EDGE_CHUCK_VOLTAGE__MIN_ERROR					6
#define  ALID__ESC_EDGE_CHUCK_VOLTAGE__MAX_ERROR					7

#define  ALID__SHUTTER_NOT_CLOSE							        8
#define  ALID__SLOT_VALVE_NOT_CLOSE			  				        9

// ...
#define  ALID__HE_PRESSURE__MAX_ERROR								11
#define  ALID__HE_CENTER_CONFIG_RANGE_ERROR							12

#define  ALID__HE_WAFER_MINIMUM_LEAK_SCCM						    14
#define  ALID__HE_WAFER_MAXIMUM_LEAK_SCCM		     				15

// ...
#define  ALID__HE_CENTER_FLOW_MIN_THRESHOLD 						21
#define  ALID__HE_CENTER_FLOW_MAX_THREASHOLD						22
#define  ALID__HE_EDGE_FLOW_MIN_THRESHOLD 							23
#define  ALID__HE_EDGE_FLOW_MAX_THREASHOLD							24

// ...
#define  ALID__HE_CENTER_PRESSURE_WARNING							25
#define  ALID__HE_EDGE_PRESSURE_WARNING								26

#define  ALID__HE_CENTER_PRESSURE_FAULT								27
#define  ALID__HE_EDGE_PRESSURE_FAULT								28

// ...
#define  ALID__ESC_CENTER_VOLTAGE__WARNING_RANGE					31
#define  ALID__ESC_EDGE_VOLTAGE__WARNING_RANGE						32

#define  ALID__ESC_CENTER_VOLTAGE__FAULT_RANGE						33
#define  ALID__ESC_EDGE_VOLTAGE__FAULT_RANGE						34

#define  ALID__ESC_CENTER_VOLTAGE__HIGH_LIMIT						35
#define  ALID__ESC_EDGE_VOLTAGE__HIGH_LIMIT							36

#define  ALID__ESC_CENTER_CURRENT__HIGH_LIMIT						37
#define  ALID__ESC_EDGE_CURRENT__HIGH_LIMIT							38

// ...
#define  ALID__HE_SET__ERROR										41
//
