#pragma once


// ...
#define ALID__PROCESS_STEP_OVERTIME							1
#define ALID__PROCESS_STABLE_OVERTIME						2
#define ALID__PROCESS_CH_INTERLOCK_ALARM					3

#define ALID__SYSTEM_INTERLOCK_SENSOR_ERROR					4
#define ALID__MFC_INTERLOCK_CLOSE_ERROR						5
#define ALID__PROCESS_RECIPE_FILE_CHANGING_NOW				6

#define ALID__CHM_PRESSURE_TOLERANCE_WARNING				7
#define ALID__CHM_PRESSURE_TOLERANCE_FAULT					8		

#define ALID__MIDDLE_PIN_UP_TIMEOUT							9

#define ALID__GAS_BOX__ERROR_SENSOR_DETECTED				10
#define ALID__CHAMBER_LID__OPEN								11
#define ALID__SYSTEM_INTERLOCK_OCCUR						12
#define ALID__PROC_RESTART_SYSTEM_INIT_ERROR				13
