#pragma once


#define  ALID__OBJECT_MODE_UNKNOWN									11

#define  ALID__JOB_ERROR__VAC_RB__NOT_STANDBY						12
#define  ALID__JOB_ERROR__TMC_CHM__NOT_STANDBY						13
#define  ALID__CLEAN_ERROR__DUMMY_PORT__NOT_EXIST					14

#define  ALID__A_ARM__CONFIG_ERROR									15
#define  ALID__B_ARM__CONFIG_ERROR									16
#define  ALID__NO_ARM__CONFIG_ERROR									17
#define  ALID__PICK_ARM__CONFIG_ERROR								18

#define  ALID__JOB_ERROR__LLx__CHECK_VAC_PRESSURE					21
#define  ALID__JOB_ERROR__PMx__CHECK_VAC_PRESSURE					23

#define  ALID__MOVE_ERROR__WAFER_CONFIRM							25
#define  ALID__USER_CHECK__WAFER_CONFIRM							26
#define  ALID__PICK_ERROR__WAFER_MITMATCH							27
#define  ALID__PLACE_ERROR__WAFER_MITMATCH							28

#define  ALID__VAC_ROBOT__NOT_STANDBY_ERROR							31
#define  ALID__VAC_TMC__NOT_STANDBY_ERROR							32
#define  ALID__PMC__NOT_AVAILABLE									33
#define  ALID__LLx__NOT_AVAILABLE									34

#define  ALID__SWAP_ERROR											35

#define  ALID__MANUAL_MOVE__ACTION_ERROR							37
#define  ALID__TOOL_CLEAR__ACTION_ERROR								38

#define  ALID__VAC_ROBOT__A_ARM__NOT_USED							40
#define  ALID__VAC_ROBOT__B_ARM__NOT_USED							41

#define  ALID__PMx_STATUS__IS_NOT_AVAILABLE							42
#define  ALID__LLx_STATUS__IS_NOT_AVAILABLE							43

#define  ALID__VAC_ROBOT__MOVE_PAUSED								45

#define  ALID__JOB_ERROR__MATERIAL_AND_PMC_PROC_TYPE_MISMATCH		47

#define  ALID__MAINT_PICK_ERROR__VAC_RB_PAUSED						48
#define  ALID__MAINT_PLACE_ERROR__VAC_RB_PAUSED						49
